### ISSUE TITLE
(not issue) how do I make it change gravity when I enter a portal in immersive portals

### ISSUE THREAD

**Issue by stupidratcreature1000** [qouteall/GravityChanger#10]
### Minecraft version

1.20.1

### Describe the issue

please

**Comment by qouteall** [comment]
In immersive portals there is a command stick of "Enable gravity changing" to a portal. Use that command stick to the portal.

**Comment by mageowl** [comment]
Is there a way to make this the default?

**Comment by qouteall** [comment]
@mageowl  In the latest version, that config option exists (not in old versions)
