### ISSUE TITLE
Gravity potion not changing rotation for mobs

### ISSUE THREAD

**Issue by kristibektashi** [qouteall/GravityChanger#17]
### Minecraft version

1.20.1

### Describe the issue

Basically https://github.com/qouteall/GravityChanger/issues/11 but for mobs instead of players. The mobs behave as if the gravity has changed in accordance to the potion effect, but they do not rotate visually. Players are unaffected by this.

Steps to reproduce:
1. Spawn a zombie (or other mob)
2. Throw it any gravity-changing potion (except down)

Expected behavior: The mob's gravity will change and it's model will also rotate to indicate that
Observed behavior: The mob's gravity does change, but it's model doesn't rotate

Note: This does not apply when using an anchor (dropping it to a zombie that can pick up items) or changing the base gravity of the mob. It only happens when using the potion effects

**Comment by Fisch37** [comment]
Changelogs for v1.1.2 say this has been fixed. If this is true, shouldn't the issue be closed?
