### ISSUE TITLE
[1.20.1 Fabric] Crash with Bumblezone's Sentry Watcher entity when opening Identity menu

### ISSUE THREAD

**Issue by TelepathicGrunt** [qouteall/GravityChanger#26]
### Minecraft version

1.20.1

### Describe the issue

I am the dev for Bumblezone and I gotten this issue report.
https://github.com/TelepathicGrunt/Bumblezone/issues/317

The short summary is a player has Bumblezone, your GravityAPI fork, and Identity mod on. When they open Identity's menu, they crash. The crash might happen when spawning Sentry Watcher too but not sure.

Here's my analysis I gave to the player in my issue report:

> Lets see. Identity iterates over the entire entity registry and tries to construct every entity.
> https://github.com/Draylar/identity/blob/2fdf47a7c8c727f05460378247ff118f868f0713/common/src/main/java/draylar/identity/api/variant/IdentityType.java#L91C35-L91C35
> 
> Sentry Watcher gets created and as part of setup, tries to orient in a cardinal direction like north, south, east, or west. Sentry Watch starts by calling getDirection() which is a vanilla method for entity and should be safe to call.
> [Bumblezone/common/src/main/java/com/telepathicgrunt/the_bumblezone/entities/nonliving/SentryWatcherEntity.java](https://github.com/TelepathicGrunt/Bumblezone/blob/d6275f68b46c325df131c047a5462a2ab547f010/common/src/main/java/com/telepathicgrunt/the_bumblezone/entities/nonliving/SentryWatcherEntity.java#L125)
> 
> Line 125 in [d6275f6](https://github.com/TelepathicGrunt/Bumblezone/commit/d6275f68b46c325df131c047a5462a2ab547f010)
> 
>  targetFacing = this.getDirection(); 
> GravityChangerAPI by quoteall tries to get a gravity component off of the Sentry Watcher. It seems GravityAPI is crashing due to null within their gravity data code but only for Sentry Watch and I have no idea why
> https://github.com/qouteall/GravityChanger/blob/819638d934911f851d04cdef13504857db9df750/src/main/java/gravity_changer/api/GravityChangerAPI.java#L101

Relevant stacktrace portions:

> java.lang.NullPointerException: Cannot invoke "dev.onyxstudios.cca._generated_.GeneratedComponentContainer.get$gravity_changer$gravity_data()" because "<parameter1>" is null
> 	at dev.onyxstudios.cca._generated_.ComponentType$gravity_changer$gravity_data.getInternal(Unknown Source)
> 	at dev.onyxstudios.cca.api.v3.component.ComponentKey.get(ComponentKey.java:86)
> 	at gravity_changer.api.GravityChangerAPI.getGravityComponent(GravityChangerAPI.java:101)
> 	at gravity_changer.api.GravityChangerAPI.getGravityDirection(GravityChangerAPI.java:31)
> 	at net.minecraft.class_1297.modify$ccb000$gravity_changer_q$redirect_getHorizontalFacing_getYaw_0(class_1297.java:11795)
> 	at net.minecraft.class_1297.method_5735(class_1297.java:3008)
> 	at com.telepathicgrunt.the_bumblezone.entities.nonliving.SentryWatcherEntity.getTargetFacing(SentryWatcherEntity.java:125)
> 	at com.telepathicgrunt.the_bumblezone.entities.nonliving.SentryWatcherEntity.method_5693(SentryWatcherEntity.java:141)
> 	at net.minecraft.class_1297.<init>(class_1297.java:297)
> 	at com.telepathicgrunt.the_bumblezone.entities.nonliving.SentryWatcherEntity.<init>(SentryWatcherEntity.java:111)
> 	at net.minecraft.class_1299.method_5883(class_1299.java:544)
> 	at draylar.identity.api.variant.IdentityType.getAllTypes(IdentityType.java:91)
> 	at draylar.identity.screen.IdentityScreen.populateRenderEntities(IdentityScreen.java:218)
> 	at draylar.identity.screen.IdentityScreen.<init>(IdentityScreen.java:54)
> 	at draylar.identity.impl.tick.MenuKeyPressHandler.tick(MenuKeyPressHandler.java:17)
> 	at draylar.identity.impl.tick.MenuKeyPressHandler.tick(MenuKeyPressHandler.java:9)

I can't really see what the crash line specifically is on but it seems specific to GravityAPI and Sentry Watcher. As background on Sentry Watcher, it is an Entity extended class that I heavily adjusted to be able to move around and slam players and mobs into walls and stuff. It does not extend Mob or LivingEntity. I do not know if any specific thing about the Sentry Watcher implementation is causing issues with GravityAPI.

**Comment by TelepathicGrunt** [comment]
User's crashlog: [crash-2023-12-12_19.08.03-client.txt](https://github.com/TelepathicGrunt/Bumblezone/files/13654504/crash-2023-12-12_19.08.03-client.txt)

**Comment by qouteall** [comment]
Cardinal components initialize the component at the end of `Entity`'s constructor. This crash seems happened inside entity's constructor, before cardinal component's initialization. I am going to change `redirect_getHorizontalFacing_getYaw_0` to make it work on non-initialized case

**Comment by TelepathicGrunt** [comment]
just checking in, was an update released with the fix? Seeing if I can close the issue report on my side.

**Comment by qouteall** [comment]
I made some related changes in version 1.2.1 that maybe fixed the issue (I didn't test)

**Comment by TelepathicGrunt** [comment]
ah so the fix is 1.20.2 and newer only. Seems identity is only on 1.20.1 so i can't test the original case that caused the crash. But testing with just Bumblezone and spawning my entity around does not crash. I'll mark this as closed
