### ISSUE TITLE
can u pls fix carpet compat issues?

### ISSUE THREAD

**Issue by ItsZer0here** [qouteall/GravityChanger#3]
carpet's auto crafting is interesting but i cant use it because carpet isnt compatible with gravity api
basically do what fusion-flux did with the 1.19.2 quilt version - 0.7.22 (changelog: https://modrinth.com/mod/gravity-api/version/0.7.22%2Bquilt#:~:text=Report-,Changelog,Fixed%20Carpet%20Compat%20Replaced%20Redirects,-Files)

**Comment by qouteall** [comment]
The versions for 1.19.x are no longer supported. If the same issue happens in the latest version, open another issue.

**Comment by ItsZer0here** [comment]
ight then imma try in 1.20.1

**Comment by ItsZer0here** [comment]
WUT DA HAIL JIT TRIPPIN THROUGH GOES HAMILTON UNBELIEVABLE STUFF IT WORKS NOW
apparently updating minecraft and the mods was the fix
