### ISSUE TITLE
1.20 released

### ISSUE THREAD

**Issue by ItsZer0here** [qouteall/GravityChanger#4]
but take your time, i can stick with 1.19.4 for now

**Comment by ItsZer0here** [comment]
(i meant take your time porting gravity api to 1.20)

**Comment by Nick1st** [comment]
We know a new versions of the game is out. I mean, this version got 7 snapshots and a RC. You normally can't miss it. (Also people start asking about new version support weeks in advance normally)

**Comment by ItsZer0here** [comment]
I'm just waiting for the 1.20 version of Gravity API.....

Em qua., 7 de jun. de 2023 20:51, Nick1st ***@***.***>
escreveu:

**Comment by qouteall** [comment]
There is no ETA.
