### ISSUE TITLE
[BUG] Sprinting when upside-down only works in the N & S compass directions

### ISSUE THREAD

**Issue by LokeYourC3PH** [qouteall/GravityChanger#6]
### Minecraft version

1.20.1

### Describe the issue

As the title says, when trying to sprint while you're upside-down (or on the walls with the N/E/S/W changers), you can only ever sprint in directions that are either going into the northern or southern compass directions. Otherwise, you get slowed down instead, and start even drifting in different directions sometimes.

**Comment by qouteall** [comment]
I cannot reproduce this issue. 
Does this issue occur with only gravity changer mod (and fabric api) in a freshly created new world?
Can you show a video about it?

**Comment by LokeYourC3PH** [comment]
No it happens when using plenty of mods, but they modify sprinting speed. Although, try it with a beacon that gives the Speed II effect, I think it should happen to you as well.

If you don't experience it then either, I will make a video of it, as it then is some incompatibility.
