### ISSUE TITLE
Gravity Commands not showing/usable in game.

### ISSUE THREAD

**Issue by onecreq** [qouteall/GravityChanger#7]
### Minecraft version

1.20.1

### Describe the issue

While in game (with just Gravity API (qoutall fork) and immersive portals) the /gravity etc. commands are not working, in that they don't even register as commands or autofill like normal commands; the text throughout the whole command stays red, and when I try to enter the command anyway it doesn't work. Yes, I spelled it right.
![image](https://github.com/qouteall/GravityChanger/assets/87343926/42bfb48e-fd75-440f-ab24-ba16a5135d1d)
  
![image](https://github.com/qouteall/GravityChanger/assets/87343926/d65409c2-c80b-4a42-b2a1-6d75883609e1)
(same command will work with the non-fork Gravity API)

(EDIT: It's worth noting, I know there are effects for the gravity directions that achieve the same thing. I've also used the gravity changer control items, anchors, and panels from the Gravity API creative tab and those work just fine)

**Comment by qouteall** [comment]
Fixed in the next version
