### ISSUE TITLE
Paintings move/don't place correctly

### ISSUE THREAD

**Issue by baconlover209** [qouteall/GravityChanger#9]
### Minecraft version

1.20.1

### Describe the issue

when placing a painting it will be moved, right, or both by 1 block.
if you reload the world the painting will continue to move.
only happens with paintings bigger than 1 block and sometimes moves diagonally.
process can move paintings far from there original spawning block if repeated
![2023-07-25_10 26 30](https://github.com/qouteall/GravityChanger/assets/69828483/d47b9a46-dd6e-4fd3-a00b-1e3a5afa6586)
![2023-07-25_10 26 38](https://github.com/qouteall/GravityChanger/assets/69828483/15300b78-4a0f-4455-b98f-035a2b6ac2f2)

![2023-07-25_10 26 49](https://github.com/qouteall/GravityChanger/assets/69828483/e92b8743-86f0-491e-b466-c07939bb2770)

**Comment by MCLover147** [comment]
Can confirm, also experiencing this bug. Very frustrating.

**Comment by qouteall** [comment]
Fixed in 1.1.0
